### ISSUE TITLE
Scripts do not work on K8S ACS

### ISSUE THREAD

**Issue by minherz** [khenidak/kubernetes-azure-managed-disks#1]
Hello,
I have tried using the scripts you showed with Azure Kubernetes container service where agents run Windows OS.
The PVC creation is delayed like forever and results in failure of the deployment script. What is a configuration of K8S cluster on which you tested your scripts?
Azure Kubernetes container service deployes 1.5.3 version of Kubernetes.
The configuration i used is
```
apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  name: sharedfast
parameters:
  skuname: Premium_LRS
  kind: dedicated
provisioner: kubernetes.io/azure-disk
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-class: sharedfast
  name: pv-dd-shared-fast-01
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
```

*kubectl version* output:
```
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.4", GitCommit:"7243c69eb523aa4377bce883e7c0dd76b84709a1", GitTreeState:"clean", BuildDate:"2017-03-07T23:53:09Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.3", GitCommit:"029c3a408176b55c30846f0faedf56aae5992e9b", GitTreeState:"clean", BuildDate:"2017-02-15T06:34:56Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```
